Rorato/src/objects/Employee__c.object
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rorato/src/objects/Employee_Skills__c.object
<CustomObject>
    <description>Employee Skills</description>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Skills</relationshipLabel>
        <relationshipName>Employee_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Employee Skills</relationshipLabel>
        <relationshipName>Employee_Skills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employee Skills</label>
    <nameField>
        <label>Employee Skills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rorato/src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DemoWork/src/classes/EController.cls
public with sharing class EController {

        @AuraEnabled
    public static List<Employee__c> findAllEmployees() {
    return [SELECT id, name,(Select id, name From Employee_Skills__r)
            FROM   Employee__c
            LIMIT 50];
    }
    
            @AuraEnabled
    public static List<Project__c> findAllProject() {
    return [SELECT id, name,(Select id, name From Employee_Skills__r)
            FROM   Project__c
            LIMIT 50];
    }
    
                @AuraEnabled
    public static List<Employee_Skills__c> findAllSkills() {
    return [SELECT id, name, Employee__r.id, Project__r.id, Project__r.Name, Employee__r.Name
            FROM   Employee_Skills__c
            LIMIT 50];
    }
    

    
    
	

}