Rorato/src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>IT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Graphic Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description: text area mandatory field</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rorato/src/objects/Employee_Skills__c.object
<CustomObject>
    <description>Employee Skills</description>
    <fields>
        <fullName>Employee_Email__c</fullName>
        <label>Employee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Skills</relationshipLabel>
        <relationshipName>Employee_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <description>Grade</description>
        <inlineHelpText>Grade</inlineHelpText>
        <label>Grade</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Employee Skills</relationshipLabel>
        <relationshipName>Employee_Skills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employee Skills</label>
    <nameField>
        <label>Employee Skills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rorato/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Employee(classic)/src/classes/TestSubmitForApprovingESkills.cls
@isTest public class TestSubmitForApprovingESkills {
  @isTest public  static void addNewEmployeeSkills()
    {
        
        
        
         Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
     	 User u = new User(Alias = 'newTes', Email='newuser@testorg.com',
       					  EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        				  LocaleSidKey='en_US', ProfileId = p.Id,
        				  TimeZoneSidKey='America/Los_Angeles', UserName='kava@esp.com');
        insert u;
        System.runAs(u) {
             Employee__c e = new Employee__c(Name='Jor',
            						Email__c='joe@example.com',
            						Description__c='Test',
            						Department__c='Iddfdfd');
        insert e;
       List<Employee__c> temp = [Select id,Name,OwnerId
                                 From Employee__c
                                 Where id=:e.id
           
       ]; 
        System.debug('*****+'+temp.get(0).OwnerId);
        
        Project__c proj = new Project__c (Name='TestProj'
            						);
        insert proj;
            
        Employee_Skills__c es = new Employee_Skills__c(Name='Test Skill',
                                                       Employee__c=e.id,
                                                       Project__c=proj.Id,
                                                       Employee_Email__c='test@test.com',
            										   Grade__c=4);
            System.debug('******'+e.Ownerid);
        	insert es;
                                                       
                                                       
            						
    }		
    }

}