Rorato/src/objects/Employee__c.object
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rorato/src/objects/Employee_Skills__c.object
<CustomObject>
    <description>Employee Skills</description>
    <fields>
        <fullName>Employee_Email__c</fullName>
        <label>Employee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Skills</relationshipLabel>
        <relationshipName>Employee_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <description>Grade</description>
        <inlineHelpText>Grade</inlineHelpText>
        <label>Grade</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Employee Skills</relationshipLabel>
        <relationshipName>Employee_Skills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employee Skills</label>
    <nameField>
        <label>Employee Skills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rorato/src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rorato/src/classes/TestSubmitForApprovingESkills.cls
@isTest public class TestSubmitForApprovingESkills {
    @isTest public static void insertNewEmployeeSkills()
    {
       

      // Retrieve two profiles, for the standard user and the system &nbsp; 
    
      // administrator, then populate a map with them.&nbsp; 
    

      Map<String,ID> profiles =new Map<String,ID>();
      List<Profile> ps = [select id, name from Profile where name = 
         'Standard User' or name ='System Administrator'];

      for(Profile p : ps){
         profiles.put(p.name, p.id);
    
      // Create the users to be used in this test.&nbsp; 
    
      // First make a new user.&nbsp; 
    

      User standard =new User(alias ='standt', 
      email='standarddduser@testorg.com', 
      emailencodingkey='UTF-8', 
      lastname='Testing', languagelocalekey='en_US', 
      localesidkey='en_US', 
      profileid = profiles.get('Standard User'), 
      timezonesidkey='America/Los_Angeles', 
      username='standar@rg.com');

      insert standard;

      // Then instantiate a user from an existing profile&nbsp; 
    

      User admin = [SELECT Id FROM user WHERE profileid = 
                    :profiles.get('System Administrator')];

      // Create some test data for testing these two users&nbsp; 
    

      List<Account> accnts = new List<Account>();
      Account a1 = 
         new Account(name='Admin Account', ownerid = admin.id);
      Account a2 = 
         new Account(name='Standard Account', ownerid = standard.id);
      accnts.add(a1);
      accnts.add(a2);
      insert accnts;

      // Confirm that the standard user cannot see the admin account&nbsp; 
    

      system.runas(standard){
         accnts.clear();
         accnts = [select id, name from account where id = :a1.id];
         system.debug(accnts.isEmpty()+' really'+accnts);
         System.assertEquals(accnts.isEmpty(), true);

      }
      // Confirm that the admin user can see the standard account&nbsp; 
    

      system.runas(admin){
         accnts.clear();
         accnts = [select id, name from account where id = :a2.id];
         System.assertEquals(accnts.isEmpty(), false);
      }
   


system.runas(admin){
         Employee_Skills__c es = new Employee_Skills__c(Name='Test Skill2',
                                                       
                                                       Employee__c='a0A36000001ygYk',

                                                       
                                                       Project__c='a0736000000Ew01',
                                                       Employee_Email__c='test@test.com',
            										   Grade__c=4);
        insert es;
    }

        
    }
}

}