Rorato/src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description: text area mandatory field</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rorato/src/objects/Employee_Skills__c.object
<CustomObject>
    <description>Employee Skills</description>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Skills</relationshipLabel>
        <relationshipName>Employee_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <description>Grade</description>
        <inlineHelpText>Grade</inlineHelpText>
        <label>Grade</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Employee Skills</relationshipLabel>
        <relationshipName>Employee_Skills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employee Skills</label>
    <nameField>
        <label>Employee Skills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rorato/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rorato/src/classes/RandomContactFactory.cls
public with sharing class RandomContactFactory {
	public static List<Employee__c> generateRandomObject(Integer numEmpl, Integer numOppsPerAcct)
	{

		List<Employee__c> emp = new List<Employee__c>();
 
        
        for(Integer i=0;i<numEmpl;i++) {
            Employee__c c = new Employee__c(Name='Employee ' + i,
            						Email__C='example@ex.com',
            						Description__c='Sample Description');
            emp.add(c);
        }
        insert emp;
        
        //List<Employee_Skills__c> es = new List<Employee_Skills__c>();
        //for (Integer j=0;j<numEmpl;j++) {
        //    Employee__c empl = emp[j];
        //    // For each employee just inserted, add skills
        //    for (Integer k=0;k<numOppsPerAcct;k++) {
        //        es.add(new Employee_Skills__c(Employee__c=empl.Name,
        //        							Name='Test skills ' + k,
        //                               Project__c='SolutionSoft',
        //                               Grade__c=3));

        //    }
        //}
        //// Insert all opportunities for all accounts.
        //insert es;

       
		return emp;

	}

}